include_recipe './cookbooks/fish/default.rb'
include_recipe './cookbooks/git/default.rb'
include_recipe './cookbooks/go/default.rb'
include_recipe './cookbooks/ghq/default.rb'
include_recipe './cookbooks/peco/default.rb'
include_recipe './cookbooks/ruby/default.rb'
include_recipe './cookbooks/nodejs/default.rb'
