include_recipe './cookbooks/curl/default.rb'
include_recipe './cookbooks/powerline-font/default.rb'
include_recipe './cookbooks/fish/default.rb'
include_recipe './cookbooks/go/default.rb'
include_recipe './cookbooks/ghq/default.rb'
include_recipe './cookbooks/peco/default.rb'
include_recipe './cookbooks/vim/default.rb'
# include_recipe './cookbooks/anyenv/default.rb'
include_recipe './cookbooks/ruby/default.rb'
include_recipe './cookbooks/python/default.rb'
include_recipe './cookbooks/docker/default.rb'
